spring:
  application:
    name: cloud-simple-ui

server:
  port: 8073
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8071/eureka/